export const LOGIN_SIGNUP_REQUEST = "LOGIN_SIGNUP_REQUEST";
export const LOGIN_SIGNUP_SUCCESS = "LOGIN_SIGNUP_SUCCESS";
export const LOGIN_SIGNUP_FAILURE = "LOGIN_SIGNUP_FAILURE";

export const ENTER_OTP_REQUEST = "ENTER_OTP_REQUEST";
export const ENTER_OTP_SUCCESS = "ENTER_OTP_SUCCESS";
export const ENTER_OTP_FAILURE = "ENTER_OTP_FAILURE";
